server:
  port: 8881
spring:
  kafka:
    bootstrap.servers: kafka0:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  datasource:
    url: jdbc:postgresql://localhost:5432/demo_db
    driverClassName: org.postgresql.Driver
    username: demo_dev_rw
    password: dev_database_passwd
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
