version: '3'

services:
  postgres:
    image: postgres:10.4

  postgres-dev:
    image: postgres:10.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "15432:15432"
    volumes:
      - ./db/dev/databases.sql:/docker-entrypoint-initdb.d/1-dev-database.sql
      - ./db/dev/roles.sql:/docker-entrypoint-initdb.d/2-dev-roles.sql