version: '3'

services:
  postgres:
    image: postgres:10.4

  postgres-dev:
    image: postgres:10.4
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "15432:15432"
    volumes:
      - ./db/dev/databases.sh:/docker-entrypoint-initdb.d/1-dev-database.sh
      - ./db/dev/roles.sh:/docker-entrypoint-initdb.d/2-dev-roles.sh